swagger: "2.0"
info:
    title: Book Service
    description: Service that provides CRUD operations for a book
    version: ""
host: localhost:8000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /book:
        post:
            tags:
                - book
            summary: postBook book
            operationId: book#postBook
            parameters:
                - name: PostBookRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/BookPostBookRequestBody'
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/BookPostBookResponseBodyResultOperation'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BookPostBookBadRequestResponseBody'
            schemes:
                - http
    /book/{bookID}:
        get:
            tags:
                - book
            summary: getBook book
            operationId: book#getBook
            parameters:
                - name: bookID
                  in: path
                  description: Book ID
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/BookGetBookResponseBody'
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/BookGetBookBadRequestResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/BookGetBookNotFoundResponseBody'
            schemes:
                - http
    /swagger.json:
        get:
            tags:
                - book
            summary: Download ./gen/http/openapi.json
            operationId: book#/swagger.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    BookGetBookBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: getBook_BadRequest_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BookGetBookNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: getBook_NotFound_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BookGetBookResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.example.book; view=default'
        type: object
        properties:
            author:
                type: string
                description: author of the book
                example: Atque adipisci quod.
            bookCover:
                type: string
                description: cover of the book
                example:
                    - 83
                    - 105
                    - 110
                    - 116
                    - 32
                    - 114
                    - 101
                    - 112
                    - 114
                    - 101
                    - 104
                    - 101
                    - 110
                    - 100
                    - 101
                    - 114
                    - 105
                    - 116
                    - 32
                    - 101
                    - 120
                    - 32
                    - 115
                    - 105
                    - 116
                    - 32
                    - 97
                    - 99
                    - 99
                    - 117
                    - 115
                    - 97
                    - 110
                    - 116
                    - 105
                    - 117
                    - 109
                    - 32
                    - 118
                    - 101
                    - 108
                    - 105
                    - 116
                    - 32
                    - 113
                    - 117
                    - 105
                    - 46
                format: byte
            id:
                type: integer
                description: ID of the book
                example: 4058199226839330147
                format: int64
            publishedAt:
                type: string
                description: cover of the book
                example: Perspiciatis eveniet fuga aut aspernatur dicta.
            title:
                type: string
                description: ' of the book'
                example: Sit illum suscipit nulla quidem.
        description: GetBookResponseBody result type (default view)
        example:
            author: Nisi cum sint.
            bookCover:
                - 67
                - 117
                - 109
                - 32
                - 111
                - 100
                - 105
                - 116
                - 32
                - 97
                - 98
                - 32
                - 100
                - 105
                - 103
                - 110
                - 105
                - 115
                - 115
                - 105
                - 109
                - 111
                - 115
                - 32
                - 105
                - 100
                - 32
                - 97
                - 109
                - 101
                - 116
                - 46
            id: 2668015636346671543
            publishedAt: Quia quo animi ullam aspernatur.
            title: Et iusto.
    BookPostBookBadRequestResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: postBook_BadRequest_response_body result type (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    BookPostBookRequestBody:
        title: BookPostBookRequestBody
        type: object
        properties:
            author:
                type: string
                description: author of the book
                example: Repellat similique.
            bookCover:
                type: string
                description: cover of the book
                example:
                    - 86
                    - 101
                    - 108
                    - 32
                    - 101
                    - 116
                    - 32
                    - 110
                    - 111
                    - 98
                    - 105
                    - 115
                    - 46
                format: byte
            id:
                type: integer
                description: ID of the book
                example: 2550908872398104110
                format: int64
            publishedAt:
                type: string
                description: cover of the book
                example: Illum culpa tempore provident laborum qui.
            title:
                type: string
                description: ' of the book'
                example: Dolores quas illum sunt quae itaque.
        example:
            author: Repellat temporibus alias.
            bookCover:
                - 78
                - 101
                - 109
                - 111
                - 32
                - 105
                - 116
                - 97
                - 113
                - 117
                - 101
                - 32
                - 102
                - 117
                - 103
                - 97
                - 32
                - 100
                - 111
                - 108
                - 111
                - 114
                - 101
                - 109
                - 32
                - 101
                - 108
                - 105
                - 103
                - 101
                - 110
                - 100
                - 105
                - 32
                - 117
                - 116
                - 46
            id: 4620104086970151444
            publishedAt: Exercitationem voluptatem aut eos cupiditate corrupti excepturi.
            title: Cumque molestiae.
    BookPostBookResponseBodyResultOperation:
        title: 'Mediatype identifier: application/vnd.goa.example.book; view=resultOperation'
        type: object
        properties:
            id:
                type: integer
                description: ID of the book
                example: 4017435239971319589
                format: int64
        description: PostBookResponseBody result type (resultOperation view) (default view)
        example:
            id: 7102583078069072775
