openapi: 3.0.3
info:
    title: Book Service
    description: Service that provides CRUD operations for a book
    version: "1.0"
servers:
    - url: http://localhost:8000/book
      description: book hosts the Book Service.
paths:
    /book:
        post:
            tags:
                - book
            summary: postBook book
            operationId: book#postBook
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/BookReq'
                        example:
                            author: Magni officia voluptatem voluptate.
                            bookCover:
                                - 85
                                - 116
                                - 32
                                - 101
                                - 116
                                - 46
                            publishedAt: Modi officia inventore aut fuga.
                            title: Voluptatum dicta molestiae veniam.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PostBookResponseBodyResultOperation'
                            example:
                                id: 6109683414823579693
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /book/{bookID}:
        get:
            tags:
                - book
            summary: getBook book
            operationId: book#getBook
            parameters:
                - name: bookID
                  in: path
                  description: Book ID
                  required: true
                  schema:
                    type: integer
                    description: Book ID
                    example: 5737638578049529029
                    format: int64
                  example: 1508401857608953804
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetBookResponseBody'
                            example:
                                author: Est et eligendi eos quo accusantium.
                                bookCover:
                                    - 67
                                    - 117
                                    - 112
                                    - 105
                                    - 100
                                    - 105
                                    - 116
                                    - 97
                                    - 116
                                    - 101
                                    - 32
                                    - 109
                                    - 97
                                    - 103
                                    - 110
                                    - 105
                                    - 32
                                    - 97
                                    - 110
                                    - 105
                                    - 109
                                    - 105
                                    - 46
                                id: 4631102261227338018
                                publishedAt: Error veniam libero omnis odit.
                                title: Ipsum quia consequatur veritatis dicta.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /swagger.json:
        get:
            tags:
                - book
            summary: Download ./gen/http/openapi.json
            operationId: book#/swagger.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        BookReq:
            type: object
            properties:
                author:
                    type: string
                    example: Deleniti est architecto qui aut dolor.
                bookCover:
                    type: string
                    example:
                        - 69
                        - 116
                        - 32
                        - 100
                        - 105
                        - 115
                        - 116
                        - 105
                        - 110
                        - 99
                        - 116
                        - 105
                        - 111
                        - 46
                    format: binary
                publishedAt:
                    type: string
                    example: Magni quam modi.
                title:
                    type: string
                    example: Sed quo omnis est dolores illum occaecati.
            description: A single book response
            example:
                author: Consequuntur molestiae et.
                bookCover:
                    - 81
                    - 117
                    - 105
                    - 32
                    - 115
                    - 105
                    - 110
                    - 116
                    - 46
                publishedAt: Est similique nobis odit.
                title: Beatae placeat.
            required:
                - title
                - author
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        GetBookResponseBody:
            type: object
            properties:
                author:
                    type: string
                    description: author of the book
                    example: Voluptas earum eaque quo dolorem repellendus.
                bookCover:
                    type: string
                    description: cover of the book
                    example:
                        - 65
                        - 99
                        - 99
                        - 117
                        - 115
                        - 97
                        - 110
                        - 116
                        - 105
                        - 117
                        - 109
                        - 32
                        - 115
                        - 101
                        - 100
                        - 46
                    format: binary
                id:
                    type: integer
                    description: ID of the book
                    example: 1940675957994074533
                    format: int64
                publishedAt:
                    type: string
                    description: cover of the book
                    example: Consectetur nulla consequatur possimus et ratione.
                title:
                    type: string
                    description: ' of the book'
                    example: Vel hic expedita.
            description: GetBookResponseBody result type (default view)
            example:
                author: Corporis nesciunt suscipit.
                bookCover:
                    - 83
                    - 101
                    - 113
                    - 117
                    - 105
                    - 32
                    - 113
                    - 117
                    - 105
                    - 97
                    - 32
                    - 101
                    - 116
                    - 32
                    - 118
                    - 111
                    - 108
                    - 117
                    - 112
                    - 116
                    - 97
                    - 116
                    - 101
                    - 32
                    - 113
                    - 117
                    - 97
                    - 115
                    - 105
                    - 46
                id: 7922113091093901608
                publishedAt: Error quis quia in.
                title: Voluptatem voluptatem et.
        PostBookResponseBodyResultOperation:
            type: object
            properties:
                id:
                    type: integer
                    description: ID of the book
                    example: 1554665296253675918
                    format: int64
            description: PostBookResponseBody result type (resultOperation view)
            example:
                id: 4822901952458110488
tags:
    - name: book
      description: The book service performs operations for books
