openapi: 3.0.3
info:
    title: Book Service
    description: Service that provides CRUD operations for a book
    version: "1.0"
servers:
    - url: http://localhost:8000/book
      description: book hosts the Book Service.
paths:
    /book:
        post:
            tags:
                - book
            summary: postBook book
            operationId: book#postBook
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/BookReq'
                        example:
                            author: Quidem asperiores.
                            bookCover:
                                - 65
                                - 100
                                - 105
                                - 112
                                - 105
                                - 115
                                - 99
                                - 105
                                - 32
                                - 113
                                - 117
                                - 111
                                - 100
                                - 46
                            id: 9193006376374536106
                            publishedAt: Sint reprehenderit ex sit accusantium velit qui.
                            title: Itaque placeat labore cum sit illum suscipit.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PostBookResponseBodyResultOperation'
                            example:
                                id: 6594385603876165635
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /book/{bookID}:
        get:
            tags:
                - book
            summary: getBook book
            operationId: book#getBook
            parameters:
                - name: bookID
                  in: path
                  description: Book ID
                  required: true
                  schema:
                    type: integer
                    description: Book ID
                    example: 3050241796954151231
                    format: int64
                  example: 4253550530100022039
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetBookResponseBody'
                            example:
                                author: Iusto eveniet id nemo eum beatae.
                                bookCover:
                                    - 67
                                    - 111
                                    - 114
                                    - 112
                                    - 111
                                    - 114
                                    - 105
                                    - 115
                                    - 32
                                    - 100
                                    - 111
                                    - 108
                                    - 111
                                    - 114
                                    - 117
                                    - 109
                                    - 32
                                    - 117
                                    - 116
                                    - 32
                                    - 101
                                    - 116
                                    - 32
                                    - 113
                                    - 117
                                    - 111
                                    - 46
                                id: 8945526493494502635
                                publishedAt: Dolorum et repellendus vero id voluptatem.
                                title: Omnis odit vero.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /book/{id}:
        patch:
            tags:
                - book
            summary: patchBook book
            operationId: book#patchBook
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    example: 575026343872706558
                    format: int64
                  example: 5565823076788288399
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/BookPathcReq'
                        example:
                            author: Ut tenetur ut inventore voluptates.
                            bookCover:
                                - 69
                                - 97
                                - 32
                                - 97
                                - 32
                                - 97
                                - 32
                                - 114
                                - 101
                                - 99
                                - 117
                                - 115
                                - 97
                                - 110
                                - 100
                                - 97
                                - 101
                                - 46
                            id: 4007170647046532603
                            publishedAt: Qui similique inventore et dolores quas.
                            title: Perferendis ut rerum.
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /swagger.json:
        get:
            tags:
                - book
            summary: Download ./gen/http/openapi.json
            operationId: book#/swagger.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        BookPathcReq:
            type: object
            properties:
                author:
                    type: string
                    example: Quo velit porro tempora consequatur atque.
                bookCover:
                    type: string
                    example:
                        - 81
                        - 117
                        - 105
                        - 32
                        - 101
                        - 120
                        - 99
                        - 101
                        - 112
                        - 116
                        - 117
                        - 114
                        - 105
                        - 32
                        - 97
                        - 98
                        - 32
                        - 101
                        - 116
                        - 32
                        - 105
                        - 108
                        - 108
                        - 117
                        - 109
                        - 32
                        - 109
                        - 97
                        - 103
                        - 110
                        - 105
                        - 32
                        - 118
                        - 101
                        - 108
                        - 105
                        - 116
                        - 46
                    format: binary
                id:
                    type: integer
                    example: 155126561843934303
                    format: int64
                publishedAt:
                    type: string
                    example: Vel nemo.
                title:
                    type: string
                    example: Eius quis a.
            description: A single book response
            example:
                author: Sint tempore quam.
                bookCover:
                    - 79
                    - 109
                    - 110
                    - 105
                    - 115
                    - 32
                    - 97
                    - 109
                    - 101
                    - 116
                    - 46
                id: 7613149752686508322
                publishedAt: Quia tenetur et officiis tenetur corporis.
                title: Et mollitia animi.
        BookReq:
            type: object
            properties:
                author:
                    type: string
                    example: Quia cum aliquid corporis.
                bookCover:
                    type: string
                    example:
                        - 80
                        - 111
                        - 114
                        - 114
                        - 111
                        - 32
                        - 118
                        - 105
                        - 116
                        - 97
                        - 101
                        - 32
                        - 118
                        - 101
                        - 108
                        - 105
                        - 116
                        - 32
                        - 108
                        - 105
                        - 98
                        - 101
                        - 114
                        - 111
                        - 46
                    format: binary
                id:
                    type: integer
                    example: 5163639737292373875
                    format: int64
                publishedAt:
                    type: string
                    example: Non quisquam delectus ea minima nihil ut.
                title:
                    type: string
                    example: Aspernatur voluptatem.
            description: A single book response
            example:
                author: Enim dolores optio animi ut.
                bookCover:
                    - 81
                    - 117
                    - 105
                    - 32
                    - 97
                    - 116
                    - 113
                    - 117
                    - 101
                    - 32
                    - 118
                    - 101
                    - 108
                    - 105
                    - 116
                    - 32
                    - 101
                    - 111
                    - 115
                    - 46
                id: 2745941563220750167
                publishedAt: Quia quos optio quae repellat rerum harum.
                title: Impedit doloremque velit.
            required:
                - title
                - author
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: false
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: false
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: false
            example:
                fault: true
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: false
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        GetBookResponseBody:
            type: object
            properties:
                author:
                    type: string
                    description: author of the book
                    example: Pariatur harum.
                bookCover:
                    type: string
                    description: cover of the book
                    example:
                        - 68
                        - 101
                        - 115
                        - 101
                        - 114
                        - 117
                        - 110
                        - 116
                        - 32
                        - 97
                        - 99
                        - 99
                        - 117
                        - 115
                        - 97
                        - 110
                        - 116
                        - 105
                        - 117
                        - 109
                        - 32
                        - 101
                        - 114
                        - 114
                        - 111
                        - 114
                        - 32
                        - 111
                        - 100
                        - 105
                        - 116
                        - 32
                        - 113
                        - 117
                        - 105
                        - 32
                        - 117
                        - 110
                        - 100
                        - 101
                        - 46
                    format: binary
                id:
                    type: integer
                    description: ID of the book
                    example: 6239455515699825532
                    format: int64
                publishedAt:
                    type: string
                    description: cover of the book
                    example: Et ex.
                title:
                    type: string
                    description: ' of the book'
                    example: Nesciunt fuga ratione error.
            description: GetBookResponseBody result type (default view)
            example:
                author: Consequatur quaerat officiis tenetur omnis.
                bookCover:
                    - 67
                    - 117
                    - 112
                    - 105
                    - 100
                    - 105
                    - 116
                    - 97
                    - 116
                    - 101
                    - 32
                    - 110
                    - 111
                    - 110
                    - 32
                    - 110
                    - 111
                    - 110
                    - 32
                    - 101
                    - 111
                    - 115
                    - 32
                    - 115
                    - 97
                    - 101
                    - 112
                    - 101
                    - 46
                id: 3103800760786290830
                publishedAt: Magnam sunt perspiciatis qui veniam.
                title: Voluptatum dolorum ipsum porro molestiae earum.
        PostBookResponseBodyResultOperation:
            type: object
            properties:
                id:
                    type: integer
                    description: ID of the book
                    example: 8212015093239399035
                    format: int64
            description: PostBookResponseBody result type (resultOperation view)
            example:
                id: 6643382422910611374
tags:
    - name: book
      description: The book service performs operations for books
