openapi: 3.0.3
info:
    title: Book Service
    description: Service that provides CRUD operations for a book
    version: "1.0"
servers:
    - url: http://localhost:8000/book
      description: book hosts the Book Service.
paths:
    /book:
        post:
            tags:
                - book
            summary: postBook book
            operationId: book#postBook
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/BookReq'
                        example:
                            author: Magni officia voluptatem voluptate.
                            bookCover:
                                - 85
                                - 116
                                - 32
                                - 101
                                - 116
                                - 46
                            id: 1839345345543455348
                            publishedAt: Modi officia inventore aut fuga.
                            title: Dicta molestiae veniam.
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/PostBookResponseBodyResultOperation'
                            example:
                                id: 6109683414823579693
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /book/{bookID}:
        get:
            tags:
                - book
            summary: getBook book
            operationId: book#getBook
            parameters:
                - name: bookID
                  in: path
                  description: Book ID
                  required: true
                  schema:
                    type: integer
                    description: Book ID
                    example: 3349249505428788113
                    format: int64
                  example: 7409940636133323045
            responses:
                "200":
                    description: OK response.
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetBookResponseBody'
                            example:
                                author: Est et eligendi eos quo accusantium.
                                bookCover:
                                    - 67
                                    - 117
                                    - 112
                                    - 105
                                    - 100
                                    - 105
                                    - 116
                                    - 97
                                    - 116
                                    - 101
                                    - 32
                                    - 109
                                    - 97
                                    - 103
                                    - 110
                                    - 105
                                    - 32
                                    - 97
                                    - 110
                                    - 105
                                    - 109
                                    - 105
                                    - 46
                                id: 4631102261227338018
                                publishedAt: Error veniam libero omnis odit.
                                title: Ipsum quia consequatur veritatis dicta.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /book/{id}:
        patch:
            tags:
                - book
            summary: patchBook book
            operationId: book#patchBook
            parameters:
                - name: id
                  in: path
                  required: true
                  schema:
                    type: integer
                    example: 3083643277633467658
                    format: int64
                  example: 139679875871339061
            requestBody:
                required: true
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/BookReq'
                        example:
                            author: Et iusto.
                            bookCover:
                                - 78
                                - 105
                                - 115
                                - 105
                                - 32
                                - 99
                                - 117
                                - 109
                                - 32
                                - 115
                                - 105
                                - 110
                                - 116
                                - 46
                            id: 2697799264669600201
                            publishedAt: Cum odit ab dignissimos id amet.
                            title: Dicta labore.
            responses:
                "204":
                    description: No Content response.
                "400":
                    description: 'BadRequest: Bad Request response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
                "404":
                    description: 'NotFound: Not Found response.'
                    content:
                        application/vnd.goa.error:
                            schema:
                                $ref: '#/components/schemas/Error'
    /swagger.json:
        get:
            tags:
                - book
            summary: Download ./gen/http/openapi.json
            operationId: book#/swagger.json
            responses:
                "200":
                    description: File downloaded
components:
    schemas:
        BookReq:
            type: object
            properties:
                author:
                    type: string
                    example: Similique cupiditate.
                bookCover:
                    type: string
                    example:
                        - 78
                        - 111
                        - 110
                        - 32
                        - 101
                        - 111
                        - 115
                        - 32
                        - 115
                        - 97
                        - 101
                        - 112
                        - 101
                        - 32
                        - 101
                        - 97
                        - 113
                        - 117
                        - 101
                        - 32
                        - 109
                        - 97
                        - 103
                        - 110
                        - 97
                        - 109
                        - 32
                        - 115
                        - 117
                        - 110
                        - 116
                        - 46
                    format: binary
                id:
                    type: integer
                    example: 174892980555228626
                    format: int64
                publishedAt:
                    type: string
                    example: Qui veniam.
                title:
                    type: string
                    example: Laboriosam consequatur quaerat officiis tenetur.
            description: A single book response
            example:
                author: Voluptatem officia quia cum aliquid.
                bookCover:
                    - 77
                    - 97
                    - 120
                    - 105
                    - 109
                    - 101
                    - 32
                    - 112
                    - 111
                    - 114
                    - 114
                    - 111
                    - 32
                    - 118
                    - 105
                    - 116
                    - 97
                    - 101
                    - 32
                    - 118
                    - 101
                    - 108
                    - 105
                    - 116
                    - 32
                    - 108
                    - 105
                    - 98
                    - 101
                    - 114
                    - 111
                    - 46
                id: 9012046878496806649
                publishedAt: Non quisquam delectus ea minima nihil ut.
                title: Error quia assumenda eaque error laboriosam.
            required:
                - title
                - author
        Error:
            type: object
            properties:
                fault:
                    type: boolean
                    description: Is the error a server-side fault?
                    example: true
                id:
                    type: string
                    description: ID is a unique identifier for this particular occurrence of the problem.
                    example: 123abc
                message:
                    type: string
                    description: Message is a human-readable explanation specific to this occurrence of the problem.
                    example: parameter 'p' must be an integer
                name:
                    type: string
                    description: Name is the name of this class of errors.
                    example: bad_request
                temporary:
                    type: boolean
                    description: Is the error temporary?
                    example: true
                timeout:
                    type: boolean
                    description: Is the error a timeout?
                    example: true
            example:
                fault: false
                id: 123abc
                message: parameter 'p' must be an integer
                name: bad_request
                temporary: true
                timeout: false
            required:
                - name
                - id
                - message
                - temporary
                - timeout
                - fault
        GetBookResponseBody:
            type: object
            properties:
                author:
                    type: string
                    description: author of the book
                    example: Voluptas perspiciatis quas iure odio.
                bookCover:
                    type: string
                    description: cover of the book
                    example:
                        - 82
                        - 101
                        - 114
                        - 117
                        - 109
                        - 32
                        - 101
                        - 117
                        - 109
                        - 46
                    format: binary
                id:
                    type: integer
                    description: ID of the book
                    example: 2648768174021329261
                    format: int64
                publishedAt:
                    type: string
                    description: cover of the book
                    example: Cupiditate molestiae doloribus aliquam.
                title:
                    type: string
                    description: ' of the book'
                    example: Sint aut est similique nobis odit.
            description: GetBookResponseBody result type (default view)
            example:
                author: Pariatur harum.
                bookCover:
                    - 68
                    - 101
                    - 115
                    - 101
                    - 114
                    - 117
                    - 110
                    - 116
                    - 32
                    - 97
                    - 99
                    - 99
                    - 117
                    - 115
                    - 97
                    - 110
                    - 116
                    - 105
                    - 117
                    - 109
                    - 32
                    - 101
                    - 114
                    - 114
                    - 111
                    - 114
                    - 32
                    - 111
                    - 100
                    - 105
                    - 116
                    - 32
                    - 113
                    - 117
                    - 105
                    - 32
                    - 117
                    - 110
                    - 100
                    - 101
                    - 46
                id: 6239455515699825532
                publishedAt: Et ex.
                title: Nesciunt fuga ratione error.
        PostBookResponseBodyResultOperation:
            type: object
            properties:
                id:
                    type: integer
                    description: ID of the book
                    example: 2745941563220750167
                    format: int64
            description: PostBookResponseBody result type (resultOperation view)
            example:
                id: 8446710582630843445
tags:
    - name: book
      description: The book service performs operations for books
