swagger: "2.0"
info:
    title: Book Service
    description: Service that provides CRUD operations for a book
    version: ""
host: localhost:8000
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /book/{bookID}:
        get:
            tags:
                - book
            summary: getBook book
            operationId: book#getBook
            parameters:
                - name: bookID
                  in: path
                  description: Book ID
                  required: true
                  type: integer
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/BookGetBookResponseBody'
            schemes:
                - http
    /swagger.json:
        get:
            tags:
                - book
            summary: Download ./gen/http/openapi.json
            operationId: book#/swagger.json
            responses:
                "200":
                    description: File downloaded
                    schema:
                        type: file
            schemes:
                - http
definitions:
    BookGetBookResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.example.book; view=default'
        type: object
        properties:
            author:
                type: string
                description: author of the book
                example: Ut et.
            bookCover:
                type: array
                items:
                    type: string
                    example:
                        - 77
                        - 111
                        - 100
                        - 105
                        - 32
                        - 111
                        - 102
                        - 102
                        - 105
                        - 99
                        - 105
                        - 97
                        - 32
                        - 105
                        - 110
                        - 118
                        - 101
                        - 110
                        - 116
                        - 111
                        - 114
                        - 101
                        - 32
                        - 97
                        - 117
                        - 116
                        - 32
                        - 102
                        - 117
                        - 103
                        - 97
                        - 46
                    format: byte
                description: cover of the book
                example:
                    - - 85
                      - 116
                      - 32
                      - 105
                      - 116
                      - 97
                      - 113
                      - 117
                      - 101
                      - 32
                      - 112
                      - 108
                      - 97
                      - 99
                      - 101
                      - 97
                      - 116
                      - 32
                      - 108
                      - 97
                      - 98
                      - 111
                      - 114
                      - 101
                      - 32
                      - 99
                      - 117
                      - 109
                      - 46
                    - - 73
                      - 108
                      - 108
                      - 117
                      - 109
                      - 32
                      - 115
                      - 117
                      - 115
                      - 99
                      - 105
                      - 112
                      - 105
                      - 116
                      - 32
                      - 110
                      - 117
                      - 108
                      - 108
                      - 97
                      - 46
                    - - 65
                      - 115
                      - 112
                      - 101
                      - 114
                      - 105
                      - 111
                      - 114
                      - 101
                      - 115
                      - 32
                      - 97
                      - 116
                      - 113
                      - 117
                      - 101
                      - 32
                      - 97
                      - 100
                      - 105
                      - 112
                      - 105
                      - 115
                      - 99
                      - 105
                      - 32
                      - 113
                      - 117
                      - 111
                      - 100
                      - 32
                      - 113
                      - 117
                      - 97
                      - 101
                      - 32
                      - 115
                      - 105
                      - 110
                      - 116
                      - 32
                      - 114
                      - 101
                      - 112
                      - 114
                      - 101
                      - 104
                      - 101
                      - 110
                      - 100
                      - 101
                      - 114
                      - 105
                      - 116
                      - 46
            id:
                type: integer
                description: ID of the book
                example: 4761504957517041764
                format: int64
            publishedAt:
                type: string
                description: cover of the book
                example: Sit accusantium velit.
            title:
                type: string
                description: ' of the book'
                example: Magni officia voluptatem voluptate.
        description: GetBookResponseBody result type (default view)
        example:
            author: Iste et iusto beatae nisi cum sint.
            bookCover:
                - - 79
                  - 100
                  - 105
                  - 116
                  - 32
                  - 97
                  - 98
                  - 32
                  - 100
                  - 105
                  - 103
                  - 110
                  - 105
                  - 115
                  - 115
                  - 105
                  - 109
                  - 111
                  - 115
                  - 32
                  - 105
                  - 100
                  - 32
                  - 97
                  - 109
                  - 101
                  - 116
                  - 46
                - - 81
                  - 117
                  - 105
                  - 97
                  - 32
                  - 113
                  - 117
                  - 111
                  - 32
                  - 97
                  - 110
                  - 105
                  - 109
                  - 105
                  - 32
                  - 117
                  - 108
                  - 108
                  - 97
                  - 109
                  - 32
                  - 97
                  - 115
                  - 112
                  - 101
                  - 114
                  - 110
                  - 97
                  - 116
                  - 117
                  - 114
                  - 46
                - - 78
                  - 101
                  - 109
                  - 111
                  - 32
                  - 112
                  - 97
                  - 114
                  - 105
                  - 97
                  - 116
                  - 117
                  - 114
                  - 32
                  - 112
                  - 101
                  - 114
                  - 102
                  - 101
                  - 114
                  - 101
                  - 110
                  - 100
                  - 105
                  - 115
                  - 32
                  - 117
                  - 116
                  - 46
                - - 80
                  - 108
                  - 97
                  - 99
                  - 101
                  - 97
                  - 116
                  - 32
                  - 117
                  - 116
                  - 32
                  - 116
                  - 101
                  - 110
                  - 101
                  - 116
                  - 117
                  - 114
                  - 46
            id: 2034847712806960597
            publishedAt: Inventore voluptates ut ea a.
            title: Perspiciatis eveniet fuga aut aspernatur dicta.
