version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: book-sql-container
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: books
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
